---
# client cert setup steps
- name: "{{ client.DN }} |Setup vars"
  set_fact:
    profile: "{{ 'usr_cert' if client.san|default('') == '' else 'usr_cert_san' }}"
    client_cn: "{{ client.DN | regex_replace('^CN=(.*?)(;.*)?$', '\\1') }}"

- name: "{{ client_cn }} |Setup filename var"
  set_fact:
    client_cn_filename: "{{ client_cn | regex_replace(' ', '_') }}"

- set_fact:
    client_pass: "{{ lookup('password', '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/password.txt') }}"
# encrypted private key
# - name: "{{ client.DN }} |Generate private key"
#   command: >
#     openssl genrsa -aes256 -passout pass:{{ signer_pass }}
#     -out "{{ authority_path }}/private/{{ client.DN }}.key" 2048
#   args:
#     creates: '{{ authority_path }}/private/{{ client.DN }}.key'

- name: "{{ client_cn }} |Generate private key"
  command: 'openssl genrsa -out "{{ authority_path }}/private/{{ client_cn_filename }}.key" 2048'
  args:
    creates: '{{ authority_path }}/private/{{ client_cn_filename }}.key'

- name: "{{ client_cn }} |PKCS8 private key"
  command: >
    openssl pkcs8 -in "{{ authority_path }}/private/{{ client_cn_filename }}.key"
    -topk8 -nocrypt -out "{{ authority_path }}/private/{{ client_cn_filename }}.pkcs8.key"
  args:
    creates: '{{ authority_path }}/private/{{ client_cn_filename }}.pkcs8.key'

- name: "{{ client_cn }} |Generate cert signing request (csr)"
  command: >
    openssl req -config "{{ authority_conf }}" -extensions {{ profile }}
    -new -passin pass:{{ authority_pass }}
    -subj "/{{ client.DN }}" -sha256 -key "{{ authority_path }}/private/{{ client_cn_filename }}.key"
    -out "{{ authority_path }}/csr/{{ client_cn_filename }}.csr.pem"
  args:
    creates: '{{ authority_path }}/csr/{{ client_cn_filename }}.csr.pem'
  environment:
    SAN: "{{ client.san | default('') }}"

- name: "{{ client_cn }} |Sign csr by authority: {{ authority_cn }}"
  command: >
    openssl ca -batch -config "{{ authority_conf }}" -extensions {{ profile }}
    -passin pass:{{ authority_pass }} -days 3650 -notext -md sha256
    -in "{{ authority_path }}/csr/{{ client_cn_filename }}.csr.pem"
    -out "{{ authority_path }}/certs/{{ client_cn_filename }}.crt"
  args:
    creates: '{{ authority_path }}/certs/{{ client_cn_filename }}.crt'
  environment:
    SAN: "{{ client.san | default('') }}"

- name: "{{ client_cn }} |Create PKCS12 keystore"
  command: >
    openssl pkcs12 -export -chain -in "{{ authority_path }}/certs/{{ client_cn_filename }}.crt"
    -inkey "{{ authority_path }}/private/{{ client_cn_filename }}.key"
    -out "{{ authority_path }}/certs/{{ client_cn_filename }}.p12"
    -name {{ client_cn_filename }} -passout pass:{{ client_pass }}
    -CAfile "{{ authority_path }}/certs/{{ authority_cn_filename }}-chain.crt"
  args:
    creates: '{{ authority_path }}/certs/{{ client_cn_filename }}.p12'

- name: "{{ client_cn }} |Create Java keystore"
  command: >
    keytool -importkeystore -destkeystore "{{ authority_path }}/certs/{{ client_cn_filename }}.jks"
    -srckeystore "{{ authority_path }}/certs/{{ client_cn_filename }}.p12" -srcstoretype pkcs12
    -alias {{ client_cn_filename }} -srcstorepass {{ client_pass }} -deststorepass {{ client_pass }} -noprompt
  args:
    creates: '{{ authority_path }}/certs/{{ client_cn_filename }}.jks'

- name: "{{ client_cn }} |Setup output folder"
  file: path={{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }} state=directory

- name: "{{ client_cn }} |Copy to output folder"
  copy:
    src: '{{ item.s }}'
    dest: '{{ item.d }}'
    remote_src: true
  with_items:
    - {
        s: '{{ authority_path }}/private/{{ client_cn_filename }}.key',
        d: '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/{{ client_cn_filename }}.key'
      }
    - {
        s: '{{ authority_path }}/private/{{ client_cn_filename }}.pkcs8.key',
        d: '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/{{ client_cn_filename }}.pkcs8.key'
      }
    - {
        s: '{{ authority_path }}/certs/{{ client_cn_filename }}.crt',
        d: '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/{{ client_cn_filename }}.crt'
      }
    - {
        s: '{{ authority_path }}/certs/{{ client_cn_filename }}.p12',
        d: '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/{{ client_cn_filename }}.p12'
      }
    - {
        s: '{{ authority_path }}/certs/{{ client_cn_filename }}.jks',
        d: '{{ playbook_dir }}/certs/{{ authority_chain }}/{{ client_cn_filename }}/{{ client_cn_filename }}.jks'
      }
