---
# Main task
- name: "Setup ./.openssl folders"
  file: path=.openssl state=directory

- name: "Setup ./certs folders"
  file: path=certs state=directory

# - name: "generate random password if necessary"
#   copy: content="{{ ansible_date_time.iso8601_micro | to_uuid }}" dest="{{ playbook_dir }}/.openssl/passwd" force=no
#
# - name: "read password file"
#   set_fact:
#     authority_password: "{{ lookup('file', '{{ playbook_dir }}/.openssl/passwd') }}"

# - debug: var=authority_password

- name: setup CAs
  include: setup_ca.yml
  with_items:
    - "{{ authorities }}"
  loop_control:
    loop_var: ca_authority
