---
- hosts: localhost
  roles:
    - cert_provisioning

  # cn: Common Name
  # dn: Distinguished Name
  # san: Subject Alternative Names
  vars:
    authorities:
      - DN: "CN=Carey Ltd CA;O=Carey Ltd;C=US"
        truststore: true
        children:
          - DN: "CN=Carey Intermediate 1;O=Carey Ltd;C=US"
            servers:
              - DN: "CN=node1.local;O=Carey Ltd;C=US"
                san: "DNS:first.node, IP:127.0.0.1"
            children:
              - DN: "CN=Carey G2;O=Carey Ltd;C=US"
                servers:
                  - DN: CN=node2.local
                    san: "IP:127.0.0.1"
                  - DN: CN=kibana.local
                    san: ""
                  - DN: CN=kibana2.local
                clients:
                  - DN: CN=logstash@logstash.local
                    san: "DNS:logstash.local"
          - DN: "CN=Carey Intermediate 2;O=Carey Ltd;C=US"
      - DN: "CN=Elastic Support Ltd CA;O=Elastic Support Ltd;C=US"
        truststore: true
        children:
          - DN: "CN=Elastic Support Intermediate 1;O=Elastic Support Ltd;C=US"
            children:
              - DN: "CN=Elastic Support G2;O=Elastic Support Ltd;C=US"
          - DN: "CN=Elastic Support Intermediate 2;O=Elastic Support Ltd;C=US"
      - DN: "CN=Example Ltd CA;O=Example Ltd;C=US"
        truststore: true
