---
- hosts: localhost
  roles:
    - cert_provisioning
  # cn: Common name
  # san: Subject Alternative Names
  vars:
    authorities:
      - DN: CN=ca_A
        children:
          - DN: CN=intr_A1_1
            servers:
              - DN: CN=first.node
                san: dns=first.node
            children:
              - DN: CN=intr_A1_2
                children:
                  - DN: CN=intr_A1_3
          - DN: CN=intr_A2
            servers:
              - DN: CN=node1.local
                san: ip=127.0.0.1
              - DN: CN=kibana.local
                san: ip=127.0.0.1
            clients:
              - DN: CN=logstash@logstash.local
                san: dns=logstash.local
      - DN: CN=ca_B
        children:
          - DN: CN=intr_B1
            children:
              - DN: CN=intr_B1_1
          - DN: CN=intr_B2
